### ISSUE TITLE
M&C files: stale?

### ISSUE THREAD

**Issue by pkgw** [HERA-Team/librarian#1]
There are various files in the librarian repo that seem to be intended for the monitor & control subsystem: `mc_rpc_client.php`, `mc_constraints.sql`, etc. Since we have a separate M&C repository now, is it correct that these files are all stale? If so let's blow them away.

**Comment by dannyjacobs** [comment]
This is a test harness Anderson made to start blocking out how Librarian would interact with M&C. If nothing uses mc_rpc than yeah, they can go. Presumably you've reconnected any place that used them?

**Comment by pkgw** [comment]
Files baleted.
