### ISSUE TITLE
file store volume used is not updating correctly

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/librarian#10]
When inserting files ~1TB of files via upload_files.py, store>used rapidly climbs to 40TB. Its not clear why

Quick fix: comment store_update in hl_rpc_handler 

Long term fix: switch store table to a VIEW where used = "select sum(size) from file". Requires an update and test across the api, web interface etc.

**Comment by dannyjacobs** [comment]
commented store_update in g4b67fd5

**Comment by dannyjacobs** [comment]
Clarification, this is an independent estimate of the space used _by the Librarian_ and should be listed alongside the total used as reported by the file system.

**Comment by dannyjacobs** [comment]
Bryna partially fixed this by added a df command to the web page. But the database is still wrong, to the volume check is not performed which invalidates the "which store should I use" function.  
Maybe this should be done in a cron job inserting to the db instead?

**Comment by bhazelton** [comment]
Danny, I think we decided to change the database table to drop that column
and just do a call to df or du when the librarian is asked "what store
should I use". I'll take a look at that call and see if I can fix it to
just use df in the same way as the webpage now does.

**Comment by dannyjacobs** [comment]
Cool, that sounds good.

On Fri, Mar 18, 2016 at 1:39 PM, bhazelton <notifications@github.com> wrote:

> Danny, I think we decided to change the database table to drop that column
> and just do a call to df or du when the librarian is asked "what store
> should I use". I'll take a look at that call and see if I can fix it to
> just use df in the same way as the webpage now does.
>
> On Fri, Mar 18, 2016 at 1:00 PM, Danny Jacobs <notifications@github.com>
> wrote:
>
> > Bryna partially fixed this by added a df command to the web page. But the
> > database is still wrong, to the volume check is not performed which
> > invalidates the "which store should I use" function.
> >
> > Maybe this should be done in a cron job inserting to the db instead?
> >
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/HERA-Team/librarian/issues/10#issuecomment-198519052
> >
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/HERA-Team/librarian/issues/10#issuecomment-198533199>
>



-- 
Arizona State University
School of Earth and Space Exploration
Low Frequency Cosmology
Phone:           (505) 500 4521
Homepage:     http://loco.lab.asu.edu/danny_jacobs/

**Comment by pkgw** [comment]
Fixed!
