### ISSUE TITLE
Show transfer status summary

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/librarian#21]
Display in some summary way, more status about uploads and downloads. The current status page says how long a specific action has been running; ie a page that says # of files and at what effective data rate.

**Comment by pkgw** [comment]
Data rate would be pretty hard to implement ... you'd need to get some kind of status report from rsync/scp, and then propagate it back to the Librarian. I'm not sure if there's a sane way to get the current data rate from rsync while it's running.

**Comment by dannyjacobs** [comment]
I think just a per-file average would be enough.  Then we'd just need to log the start and stop times. We already know the file size.

**Comment by pkgw** [comment]
[I added some basic reporting.](https://github.com/HERA-Team/librarian/commit/799ecda0e2c316095b22645cc24b9d5bb4e34352)

**Comment by pkgw** [comment]
This information isn't being exposed in the web interface for the Librarian itself, but it's being logged to the M&C database and showing up in the HERA dashboard, which seems to be working pretty well. So I'm going to close this issue.
