### ISSUE TITLE
Duplicated client libraries

### ISSUE THREAD

**Issue by pkgw** [HERA-Team/librarian#3]
Right now, the repo contains client libraries written in both Python and PHP. As far as I can see, there's no particular *need* for the client programs to be written in PHP.

IMO we should port them to Python for consistency with everything else. The Python layer should also be installed as a Python package `hera_librarian` so other code can use it in the standard way.

**Comment by dannyjacobs** [comment]
Aren't the PHP libraries used by the web page?

**Comment by pkgw** [comment]
The `*.inc` files are, but not `hl_rpc_client.php` — that's only used by the command-line programs. Most of those programs — `copier`, `copy_maker`, `copy_master` — could just as well be written in Python, as far as I can see.

`db_init` and `copy_master` are iffier since they're run as standalone programs, but access the Librarian database directly. If you ask me it'd still be better to implement `copy_master` in Python — PHP is a pretty gross language! And it'd only be a tiny amount of work to mirror the code that loads the database config.

**Comment by dannyjacobs** [comment]
Yeah, command line programs in php seems a bit much. It was only used because thats what Anderson  codes most quickly in.
My hope was that we could have a common toolset for M&C and Librarian. If you're thinking of swapping out the db interface, why not use alchemy etc?

**Comment by pkgw** [comment]
Well, the model seems to be that the RPC server — written in PHP — is the only thing that knows about or touches the database, as much as possible. So hopefully *client* Python code doesn't need an ORM at all. The  `copy_master` and `db_init` programs are the exception since they're not the RPC server but they do touch the database directly.

**Comment by pkgw** [comment]
PHP libraries are superseded after the rewrite.
