### ISSUE TITLE
trouble using quick setup guide

### ISSUE THREAD

**Issue by caseyjlaw** [HERA-Team/librarian#75]
I'm interested in playing with the librarian for some projects at OVRO. I've had some trouble getting a simple test working, though.

The server docs are great and I'm mostly using this one:
https://github.com/HERA-Team/librarian/blob/main/librarian_server/README.md#quick-and-dirty-guide-for-installing-and-testing-a-librarian-server. I have tried two backends: sqlite (in memory) and postgresql. The example json config file suggests using sqlite, while the docs themselves note that postgresql is actually used most. I have tried both without success.

First, I edited the config json file to use sqlite (`"SQLALCHEMY_DATABASE_URI": "sqlite:///test.db"`), I run the alembic upgrade command and get this error:
```
> alembic upgrade head
...
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "ALTER": syntax error
```

A little googling suggests that "ALTER" is not supported by sqlite. If so, do you have any suggestions for getting alembic to work with sqlite?

Second, I edited to use postgresql `"SQLALCHEMY_DATABASE_URI": "postgresql://localhost/librarian_test"` and then I run alembic upgrade and get this error:

```
> alembic upgrade head
...
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) fe_sendauth: no password supplied
```

A little googling suggests that postgresql authentication configuration, but I can't get that to work. Any guidance on how to configure?

**Comment by pkgw** [comment]
Hey Casey!

The sqlite example in the config file is probably a bit misleading — with some effort one could probably get it to work with the Librarian, but I would expect it to require some hacking. Unless you're strongly motivated to add that capability I think that the best path forward is to focus on Postgres. 

So. For your Postgres issue, I agree that it is probably some authentication issue that isn't specific to the Librarian. Have you tried specifying a password using the standard URL syntax as per

https://docs.sqlalchemy.org/en/14/core/engines.html#postgresql

?

I've never felt like I've really figured out Postgres authentication configuration. Historically I've sometimes had to manually add a line to enable "Unix Domain socket" authentication with a new `local` line in `pg_hba.conf`:

https://www.postgresql.org/docs/13/auth-pg-hba-conf.html

And then this form of URL to get SQLAlchemy to use the Unix Domain approach:

https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#unix-domain-connections

You could also try configuring your server to use "trust" authentication and basically ignore password stuff altogether, presuming that you're running on a single-user machine:

https://gist.github.com/p1nox/4953113
https://www.postgresql.org/docs/current/auth-trust.html

**Comment by caseyjlaw** [comment]
Thanks, Peter. I went with an anaconda installation for postgres and I'm getting to the point where I can run the librarian server. 
I found this gist helpful: https://gist.github.com/gwangjinkim/f13bf596fefa7db7d31c22efd1627c7a.
