### ISSUE TITLE
recommendations for bulk upload

### ISSUE THREAD

**Issue by caseyjlaw** [HERA-Team/librarian#78]
I have a working librarian on a server that already hosts a bunch of (non-HERA!) data. I can successfully upload a README, see it in the web interface, and use the CLI to search for it. All nice things.
My goal is to demo the ingestion of a few data products so we can basically have the database and web interface features. Not much need for multi-librarian or staging or all that fancy stuff. I'd mostly like to have a reliable way of identifying, searching, and tracking our files.
Two questions:
- Would you recommend I use the `librarian upload` feature when ingesting lots of files on the *same server* as the librarian? I gather that it is using ssh to go to localhost and move files, which seems inefficient.
- Do you have suggestions for naming files, if I do not use HERA convention? For example, I have maybe four types of files (csv, FITS, MS, obscure binary) and maybe one of each is stored in a directory with a unique date. Would you recommend I use `--nul-obsid` and define a naming convention that appends the date to the file name? Any tips on this front would be welcome.

**Comment by pkgw** [comment]
Hey Casey!

As for your first question, the [`librarian add-obs`][lao] command can register already-existing files with the Librarian, circumventing the upload process. It's been a little while so I forget what quirks it might have but I don't think it does anything too surprising. I'm afraid the documentation is a bit lacking, though :-/

[lao]: https://github.com/HERA-Team/librarian/blob/3e64efeeb7715f3565b98d4d61b66ef8e4262115/hera_librarian/cli.py#L202

For naming conventions, @plaplant might have the freshest perspective. But: if there's some kind of lowlevel, obsid-like concept that usefully groups your files together, then I'd recommend trying to figure out a naming scheme that helps you leverage it. This aspect of the Librarian design is quite specialized for the way that HERA does things right now, but I always thought that it would be nice to make the functionality a bit more generic. If there's an impedance mismatch between how your data group themselves and the HERA/Librarian model, it might even be helpful and reasonable to fork the code to align them better.

**Comment by caseyjlaw** [comment]
Thanks, Peter!
I think `add-obs` is what I need. I noticed a few issues with that code (for example, `--null-obsid` was not supported), so I created #79.
I'm still running into issues with file names and checks that are run on them. I suspect I am not fully understanding the theory and/or nomenclature. I'll keep playing and raise issues when I have something. I think forking is a good idea for naming issues.
I think you could close this issue.

**Comment by pkgw** [comment]
It took me a minute to re-find the right part of the docs, so in case you haven't seen it, the [Ingesting](https://github.com/HERA-Team/librarian/blob/main/docs/Ingesting.md) documentation file has some remarks about how the filename/obsid grouping works.
