### ISSUE TITLE
Avoid "site" terminology in ~/.hl_client.cfg and related bits

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/librarian#8]
source_to_site is a terrible name but "site" is overloaded and counterproductively anti-descriptive. The variable should be renamed.

**Comment by pkgw** [comment]
Most recent code now calls this parameter the "connection", but the code still needs to be reviewed to strip out the last vestiges of this.

**Comment by pkgw** [comment]
Fixed in c3ea1a16.
